### ISSUE TITLE
Deployment not successful even after using polygon infura

### ISSUE THREAD

**Issue by racetrack0616** [truffle-box/polygon-box#6]
![image](https://user-images.githubusercontent.com/68948218/137679513-14df614c-20dc-4449-b4ee-93e685d27a36.png)
As suggested in [https://github.com/trufflesuite/truffle/issues/4240#issuecomment-918628110](https://github.com/trufflesuite/truffle/issues/4240#issuecomment-918628110) I used polygon infura key and its url for deployment. I tried with **polygon-box** which is nothing but a very small contract and it also results same issue.
![image](https://user-images.githubusercontent.com/68948218/137688572-bba27609-5c61-407c-ac25-61d9a218f034.png)

I used same truffle setting but my contracts were not deployed as you can see in the screenshot attached. Even initial migration is not deploying.
Here is my config
![image](https://user-images.githubusercontent.com/68948218/137679898-99ba91bc-8f13-4bc1-aa5b-a1b504dfe66b.png)

**Comment by PxGnome** [comment]
Did you solve the issue? We were able to deploy to Mumbai but not mainnet using infura. Used pretty similar settings to you.

If anyone can successfully deploy on mainnet would love to hear

**Comment by racetrack0616** [comment]
Like you said, YES to Mumbai but not yet in Polygon Mainnet. :(

**Comment by its-everdred** [comment]
I wasn't able to reproduce this, migrating with infura worked on both mumbai and polygon mainnet.

@racetrack0616 @PxGnome Do you mind updating your gas settings as outlined here: https://github.com/truffle-box/polygon-box/issues/4#issuecomment-983475812

Please report back and let us know if that worked.  Thank you!

**Comment by johnbisc** [comment]
Unknown network "$npm_config_network". See your Truffle configuration file for available networks.
Truffle v5.4.22 (core: 5.4.22)
Node v16.13.0

using :  npm run migrate:polygon --network=polygon_infura_testnet --reset

**Comment by fainashalts** [comment]
@johnbisc can you try the same command but put your network name in quotes?

**Comment by illing2005** [comment]
I'm having the same issue. 
Deployment on testnet works fine but on mainnet it times out and nothing happens.

I tried increasing the gas price but that didn't help.
Any ideas?

![Screenshot from 2022-02-19 13-08-47](https://user-images.githubusercontent.com/6603781/154800170-a2cfb173-546e-4c9e-bfb1-3c01415e2397.png)

**Comment by its-everdred** [comment]
@illing2005 it is not uncommon for polygon mainnet to experience times of high bandwidth resulting in timeout issues.  Do you mind trying this again and seeing if this was a momentary issue or if it's still persisting?

**Comment by its-everdred** [comment]
I'm going to close this for issue maintenance, but please let us know and open a new issue if you are still encountering this  @illing2005 @racetrack0616
